### ISSUE TITLE
enqueue-batch fails when command lines exceed 256k for one batch

### ISSUE THREAD

**Issue by ryanwitt** [suredone/qdone#29]
## Steps to reproduce

1. Create a file with 10 lines, each command should be 100kb long

2. Try to enqueue it

```
$ ./qdone enqueue-batch too-big.txt
Creating fail queue test_failed
Creating queue test
TypeError: Cannot read property 'Failed' of undefined
    at /Users/ryan/src/qdone-master/src/enqueue.js:128:17
    at _fulfilled (/Users/ryan/src/qdone-master/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/ryan/src/qdone-master/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/ryan/src/qdone-master/node_modules/q/q.js:816:13)
    at /Users/ryan/src/qdone-master/node_modules/q/q.js:624:44
    at runSingle (/Users/ryan/src/qdone-master/node_modules/q/q.js:137:13)
    at flush (/Users/ryan/src/qdone-master/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
bash: update_terminal_cwd: command not found
```

## Expected behavior

Large command lines should enqueue in an appropriate number of api calls (2 commands per api call, in this test case).

**Comment by ryanwitt** [comment]
Test case:

[too-big.txt](https://github.com/suredone/qdone/files/1834319/too-big.txt)
