### ISSUE TITLE
Missing region in config

### ISSUE THREAD

**Issue by JoaquinCicetti** [suredone/qdone#50]
I'm getting this ConfigError from aws-sdk
It seems like it's not taking the region from the ```.aws/credentials``` file

I fixed it by adding a new ENV called AWS_REGION to the project

```
Error [ConfigError]: Missing region in config
at Request.VALIDATE_REGION (.../node_modules/qdone/node_modules/aws-sdk/lib/event_listeners.js:92:45)
at Request.callListeners (..../node_modules/qdone/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at callNextListener (..../node_modules/qdone/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
at ..../node_modules/qdone/node_modules/aws-sdk/lib/event_listeners.js:86:9
at finish (..../node_modules/qdone/node_modules/aws-sdk/lib/config.js:349:7)
at ..../node_modules/qdone/node_modules/aws-sdk/lib/config.js:391:9
at Object.<anonymous> (..../node_modules/qdone/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:111:13)
at Object.arrayEach (..../node_modules/qdone/node_modules/aws-sdk/lib/util.js:516:32)
at resolveNext (..../node_modules/qdone/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:110:20)
at ..../node_modules/qdone/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:126:13 {
  code: 'ConfigError',
  time: 2022-12-21T16:32:00.266Z
}
```

**Comment by ryanwitt** [comment]
The region needs to be in the `.aws/config` file instead of `.aws/credentials`. Not 100% sure why the SDK splits them, but maybe it's to isolate the file containing secrets.

See https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html
